<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-3C4SJB2" failures="1" tests="3" name="Default test" time="31.97" errors="0" timestamp="2024-09-24T08:51:20 IST">
  <testcase classname="com.sevenrmartsupermarket.tests.SubCategoryTest" name="clickOnNew" time="2.768">
    <skipped/>
  </testcase> <!-- clickOnNew -->
  <testcase classname="com.sevenrmartsupermarket.tests.SubCategoryTest" name="clickOnNew" time="3.228">
    <skipped/>
  </testcase> <!-- clickOnNew -->
  <testcase classname="com.sevenrmartsupermarket.tests.SubCategoryTest" name="clickOnNew" time="4.156">
    <failure type="java.lang.AssertionError" message="expected [Add Sub Category] but found [Add 1Sub Category]">
      <![CDATA[java.lang.AssertionError: expected [Add Sub Category] but found [Add 1Sub Category]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.sevenrmartsupermarket.tests.SubCategoryTest.clickOnNew(SubCategoryTest.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- clickOnNew -->
  <testcase classname="com.sevenrmartsupermarket.tests.SubCategoryTest" name="enterSubCategoryInfo" time="0.0">
    <ignored/>
  </testcase> <!-- enterSubCategoryInfo -->
  <testcase classname="com.sevenrmartsupermarket.tests.SubCategoryTest" name="verifySubCategoryheader" time="0.0">
    <ignored/>
  </testcase> <!-- verifySubCategoryheader -->
</testsuite> <!-- Default test -->
